# Do not edit this file. It is automatically generated by 'build-configs'.

default:
  @just --list

composer *args:
  just _exec php composer {{ args }}

alias phpunit := test

test *args:
  just _run phpunit {{ args }}

drush *args:
  just _exec php drush {{ args }}

install *args:
  just _exec php drush site:install -y {{ args }}




_exec +args:
  docker compose exec {{ args }}

_run command *args:
  docker compose run --rm --no-deps --entrypoint {{ command }} --tty php {{ args }}
